package com.gomezdevlopment.focus_lofimusic.ui.song_elements

const val bedtimeAfterACoffeeArt = "https://i.imgur.com/5uuoc1d.png"
const val blossomArt = "https://i.imgur.com/Rjb05O1.jpg"
const val embraceArt = "https://i.imgur.com/j8zzftR.jpg"
const val fluidArt = "https://i.imgur.com/42oH6ys.jpg"
const val herbalTeaArt = "https://i.imgur.com/nTikg93.png"
const val lofiStudyArt = "https://i.imgur.com/oQlnrrV.jpg"
const val sandCastlesArt = "https://i.imgur.com/KjBQNnm.png"
const val smoresArt = "https://i.imgur.com/ykvL4Zm.png"

const val distantArt = "https://i.imgur.com/zlw0VHY.png"
const val etherealArt = "https://i.imgur.com/AloVMIc.png"
const val fragileArt = "https://i.imgur.com/Ni7rRN6.png"
const val interplanetaryTripArt = "https://i.imgur.com/9nEO3TH.png"
const val jazzaddictsIntroArt = "https://i.imgur.com/BqCwXKV.png"
const val missingTheStreetArt= "https://i.imgur.com/VcOLDvC.png"
const val missingYouArt = "https://i.imgur.com/jw5GLUH.png"
const val noTurningBackArt = "https://i.imgur.com/BYEvSxc.png"
const val underwaterArt = "https://i.imgur.com/cX2CtVo.png"
const val sorrowArt= "https://i.imgur.com/TibFb0w.png"
const val odysseyArt = "https://i.imgur.com/B3CUFQF.png"
const val reverseArt = "https://i.imgur.com/fv0FfNE.png"
const val sunShinesThroughTheLeavesArt = "https://i.imgur.com/zQKqxMO.png"